version: "3"

services:
  webui: 
    build: "../angular/"
    container_name: gtui1
    restart: always
    ports:
      - "8080:80"
    depends_on: 
      - webserver
    links:
      - webserver

  webserver: 
    build: "../webapi/"
    container_name: gtweb1
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    volumes:
      - db-data:/App/data

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/ianfoster/dev/data
