/**
 * Ianf.Fittrack.Webapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ExerciseType = 0 | 1 | 2 | 3 | 4;

export const ExerciseType = {
    NUMBER_0: 0 as ExerciseType,
    NUMBER_1: 1 as ExerciseType,
    NUMBER_2: 2 as ExerciseType,
    NUMBER_3: 3 as ExerciseType,
    NUMBER_4: 4 as ExerciseType
};